import type { Metadata } from "next";
import "./globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { Toaster } from "react-hot-toast";
import { Header } from "../components/shared/Header";
import { Footer } from "../components/shared/Footer";

// TODO:metadataの設定を行う
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  if (!hasLocale(routing.locales, lang)) {
    notFound();
  }

  // 言語ファイルの読み込み
  const messages = await getMessages();
  return (
    <html lang={lang}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+1p:wght@400;500;700;800;900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-mplus bg-base flex flex-col">
        <NextIntlClientProvider messages={messages}>
          <Header />
          <main className="h-full">{children}</main>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 2000,
            }}
          />
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
